llm:
  provider: llama2
  config:
    model: 'snowflake/snowflake-arctic-instruct'
    temperature: 0.5
    max_tokens: 3000
    top_p: 1
    stream: true


embedder:
  provider: huggingface
  config:
    model: 'snowflake/arctic-embed-l'